from .pessoa import Pessoa
from .contato import Contato
from .cliente import Cliente
from .endereco import Endereco
from .fornecedor import Fornecedor
from .funcionario import Funcionario
from .produto import Produto
from .vende import Vende
from .compra import Compra